'use strict';

var React = require('react-native');

var {
  StyleSheet,
} = React;

module.exports = StyleSheet.create({
    texB: {
      alignItems: 'center',
      textAlign:'center',
      textAlignVertical:'center',
      color:'black',
      fontSize: 18,
      height:60,
  
    },
    icnB: {
      alignItems: 'center',
      textAlign:'center',
      textAlignVertical:'center',
      color:'black',
      fontSize: 18,
      height:40,
  
    },
    disB: {
      alignItems: 'center',
      textAlign:'center',
      textAlignVertical:'center',
      color:'black',
      fontSize: 18,
      height:80,
      color:'red',
    },
    supercontainer: {
      flex: 5,
      flexDirection: 'column',
      justifyContent: 'center',
  
    },
    textcontainer: {
      flex: 2.3,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
    },
    buttoncontainerA:{
      flex:0.1,
      flexDirection: 'row',
      justifyContent: 'space-around',
      alignItems: 'center',
      backgroundColor:'#f4cccc',
      margin:5,
      borderRadius:10,
      padding:5,
      borderWidth:2,
      borderColor:'#ff7777',
    },
    buttoncontainerB:{
      flex:0.1,
      flexDirection: 'row',
      justifyContent: 'space-around',
      alignItems: 'center',
      backgroundColor:'#ccf4cc',
      margin:5,
      borderRadius:10,
      padding:5,
      borderWidth:2,
      borderColor:'#33ff33',
    },
    searchBox: {
      flex:0.1,
      flexDirection: 'row',
      justifyContent: 'space-around',
      alignItems: 'center',
      backgroundColor:'#cccccc',
      margin:5,
      borderRadius:10,
      padding:5,
      borderWidth:2,
      borderColor:'#666666',
    },
    hw: {
      fontSize: 24,
      textAlign: 'center',
      marginTop:25,
    },
    searchF:{
      width:500,
      backgroundColor:'#ffffff22',
      flex:0.5,
      height:60,
      alignItems: 'center',
      textAlign:'center',
      textAlignVertical:'center',
      borderRadius:2,
      color:'black',
      fontSize: 18,
      borderColor:'#e06666',
  
    },
    aBtntext:{
      backgroundColor:'#ffffff22',
      flex:0.4,
      height:60,
      alignItems: 'center',
      textAlign:'center',
      textAlignVertical:'center',
      borderRadius:2,
      color:'black',
      fontSize: 18,
      borderColor:'#e06666',
  
    },
    aBtnicon:{
      backgroundColor:'#ffffff22',
      flex:0.12,
      height:46,
      alignItems: 'center',
      textAlign:'center',
      textAlignVertical:'center',
      borderRadius:100,
      color:'black',
      fontSize: 20,
      borderColor:'#000000',
      borderWidth:2,
    },
    aBtndist:{
  
      flex:0.15,
      height:80,
      alignItems: 'center',
      textAlign:'center',
      textAlignVertical:'center',
      borderRadius:50,
      color:'red',
      fontSize: 20,
      borderColor:'#e06666',
    },
    supercontainer: {
        flex: 5,
        flexDirection: 'column',
        justifyContent: 'center',
    
      },
      textcontainer: {
        flex: 2.3,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
      },
      buttoncontainer:{
        flex: 0.9,
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
        backgroundColor: '#fff',
      },
      hw: {
        fontSize: 24,
        textAlign: 'center',
        marginTop:25,
      },
      row1btn:{
        backgroundColor:'#cd3c29',
        flex:0.4,
        height:120,
        alignItems: 'center',
        textAlign:'center',
        textAlignVertical:'center',
        borderRadius:10,
        color:'white',
        fontSize: 20,
    
      },
      row2btn:{
        backgroundColor:'#69a84f',
        flex:0.4,
        height:120,
        alignItems: 'center',
        textAlign:'center',
        textAlignVertical:'center',
        borderRadius:10,
        color:'white',
        fontSize: 20,
      },
      row3btn:{
        backgroundColor:'#3d85c6',
        flex:0.4,
        height:120,
        alignItems: 'center',
        textAlign:'center',
        textAlignVertical:'center',
        borderRadius:10,
        flexWrap:'wrap',
        color:'white',
        fontSize: 20,
      },
  });
